In [21]:
#import numpy package
import numpy as np

#Creating array using arange() function
arr=np.arange(5,61,5)

#reshaping array for 2D 
arr=arr.reshape(4,3)

#printing array
print(arr)


[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]
