In [1]:
#import numpy package
import numpy as np

#Creating array using arange() function with values from 11 to 28
arr=np.arange(11,28,2)

#reshaping array for 2D 
arr=arr.reshape(3,3)

#printing array
print(arr)


[[11 13 15]
 [17 19 21]
 [23 25 27]]
